services:
  db:
    image: postgres:latest
    container_name: log-service-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: log-service
    networks:
      - log-service-network
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-data:/var/lib/postgresql/18/main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d log-service"]
      interval: 5s
      timeout: 5s
      retries: 5

  log_generator:
    build:
      context: ./log_generator
      dockerfile: Docker/Dockerfile
    image: log-generator
    container_name: log-generator
    ports:
      - "5000:5000"
    networks:
      - log-service-network

  log_process:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./log_process
      dockerfile: Docker/Dockerfile
    image: log-process
    container_name: log-process
    ports:
      - "5001:5001"
    networks:
      - log-service-network
    volumes:
      - pg-data:/var/lib/postgresql/18/main

  stats_display:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./stats_display
      dockerfile: Docker/Dockerfile
    image: stats_display
    container_name: stats-display
    ports:
      - "5002:5002"
    networks:
      - log-service-network
    volumes:
      - pg-data:/var/lib/postgresql/18/main

networks:
  log-service-network:
    driver: bridge

volumes:
  pg-data:
