apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: log-process-service.test
      http:
        paths:
          - path: /stats-display
            pathType: Prefix
            backend:
              service:
                name: stats-display-service
                port:
                  number: 5002
