apiVersion: v1

kind: Service

metadata:
  name: log-generator-service
  namespace: default

spec:
  type: ClusterIP
  selector:
    app: log-generator
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
