apiVersion: apps/v1

kind: Deployment

metadata:
  name: db-deployment
  namespace: default

spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service-db
  template:
    metadata:
      labels:
        app: log-service-db
    spec:
      containers:
        - name: log-service-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "log-service"
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/18/main
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-pvc
