apiVersion: v1

kind: Service

metadata:
  name: log-process-service
  namespace: default

spec:
  type: ClusterIP
  selector:
    app: log-process
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
