apiVersion: apps/v1

kind: Deployment

metadata:
  name: stats-display-deployment
  namespace: default

spec:
  replicas: 1
  selectors:
    matchLabels:
      app: stats-display
  template:
    metadata:
      labels:
        app: stats-display
    containers:
      - name: stats-display
        image: alirezahme96/stats-display:latest
        ports:
          - containerPort: 5002
