apiVersion: v1

kind: Service

metadata:
  name: stats-display-service
  namespace: default

spec:
  type: ClusterIP
  selector:
    app: stats-display
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
